spring:
  profiles:
    active: local
  application:
    name: dong

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      jdbc-url: jdbc:h2:tcp://localhost/~/dong
      username: sa
      password:
      driver-class-name: org.h2.Driver
  #      jdbc-url: jdbc:h2:tcp://localhost/~/springbatch

  batch:
    job:
      enabled: true
      name: ${job.name:NONE}

    jdbc:
      initialize-schema: always

  jpa:
    #    hibernate:
    #      ddl-auto: create
    properties:
      hibernate:
        #        #        show_sql: true # System.out?? ???.
        format_sql: true
  ##        default_batch_fetch_size: 4

##############
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
      name: ${job.name:NONE}

#      name: httpJob

  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
#        #        show_sql: true # System.out?? ???.
        format_sql: true
##        default_batch_fetch_size: 4

---

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace